name: E2E Preservation tests

on:
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Mon-Fri 8am utc
    - cron: '0 8 * * 1-5'

permissions:
  id-token: write  # required for OIDC / AWS
  contents: read   # This is required for actions/checkout

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.S3_IAM_ROLE }}
          aws-region: eu-west-1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=frontendtests
        env:
          CI: 'true'
          FRONTEND_BASE_URL: ${{vars.FRONTEND_BASE_URL}}
          FRONTEND_USERNAME: ${{vars.FRONTEND_USERNAME}}
          FRONTEND_PASSWORD: ${{secrets.FRONTEND_PASSWORD}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          SLACK_CHANNEL: ${{vars.SLACK_CHANNEL}}
          API_CLIENT_ID: ${{secrets.API_CLIENT_ID}}
          API_CLIENT_SECRET: ${{secrets.API_CLIENT_SECRET}}
          API_TENANT_ID: ${{secrets.API_TENANT_ID}}
          GITHUB_REPORT_OUTPUT: 'https://d1o8q7gs2alph4.cloudfront.net/${{github.repository}}/${{ github.head_ref || github.ref_name }}/index.html'


      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Archive arifacts
        if: always()
        uses: digirati-co-uk/digirati-ops-actions/.github/actions/archive-artifacts@main
